### ISSUE TITLE
Following installation instruction without electron

### ISSUE THREAD

**Issue by fulmicoton** [strangerlabs/tantivy#1]
After running `npm i`, I get the following error.

```
 nodemon@1.18.10 postinstall /home/paul/git/tantivy-search/tantivy-node/node_modules/nodemon
> node bin/postinstall || exit 0

Love nodemon? You can now support the project via the open collective:
 > https://opencollective.com/nodemon/donate


> @strangerlabs/tantivy@0.1.0 install /home/paul/git/tantivy-search/tantivy-node
> npm run build-electron


> @strangerlabs/tantivy@0.1.0 build-electron /home/paul/git/tantivy-search/tantivy-node
> npx electron-build-env neon build tantivy

could not determine electron version
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @strangerlabs/tantivy@0.1.0 build-electron: `npx electron-build-env neon build tantivy`
npm ERR! Exit status 1
npm ERR! 
```

It would be awesome if it was possible to use your tantivy bindings independently of electron.

**Comment by TheCallSign** [comment]
Thank you for making Tantivy!

I've publish an update to npm. 
Writing these bindings has been a bit of experiment. Let me know if it works.

**Comment by fulmicoton** [comment]
Cool.

So now, `npm install @strangerlabs/tantivy` works, but the native lib is not built, so that 
when I try to import your package I get the following error.


```
 Cannot find module './lib'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/paul/git/tantivy-search/tantivy-node/node_modules/@strangerlabs/tantivy/index.js:1:77)
```

Is there an extra step to it?

**Comment by fulmicoton** [comment]
Btw, I discovered this project randomly, searching for stuff in github. The bindings look awesome, and I suspect a lot of ppl in node community might be interested by it.

Keep up the good work!

**Comment by TheCallSign** [comment]
Heya
This is something related to publishing binaries to NPM. I'm going to have that working soon. I haven't worked with native packages on npm before so it has been a bit of an adventure. 

Cheers
